# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af62f63f9bc2930e25679cbeeeef802af881d06e4dae23d5f59c7a5d3317f1e806d73e3e023dc92ac22f57375b43f36fe53c0813e536a97828f7ea5312741581

test:
  secret_key_base: f6a778bb00df50408482dcf78847fa3e5a5569f682db7e7695568a55a47a40015367fbf71c7057642bc5313dca514269686590bc545d866532ec21a848b5bb30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
